# .github/workflows/hello-ci.yml
name: Hello CI

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo "👋 Hello from GitHub Actions!" && exit 1
